### ISSUE TITLE
datasets problem

### ISSUE THREAD

**Issue by wfs233** [NUSTM/FMNERG#2]
![3](https://github.com/NUSTM/FMNERG/assets/98298502/a7df99c8-da0d-41ce-9c4b-8a08bfe7b5cb)

![4](https://github.com/NUSTM/FMNERG/assets/98298502/2d6f5eb1-4b02-4022-8988-fe831dc6dbe4)

Are these 0KB files normal?

**Comment by zyLiRere** [comment]
The size of individual files mostly ranges between 200-300kb. It seems like you haven't downloaded the complete file. If downloading from GitHub is inconvenient, we've uploaded the features extracted by VinVL to [Google Drive](https://drive.google.com/file/d/1wJltKcB2IVfNkH5hmjc2Dz1dlH1hndEM/view?usp=sharing) and [Baidu Netdisk](https://pan.baidu.com/s/1QqjOlAAjCqAk_qL6ejeARw?pwd=TwVi)  (code: TwVi).

**Comment by zyLiRere** [comment]
We've encountered an issue with the dataset upload and will promptly rectify it. Your observations are greatly appreciated, and we extend our thanks!

**Comment by zyLiRere** [comment]
You can access the features by downloading them through the following links:  [Google Drive](https://drive.google.com/drive/folders/1w7W4YYeIE6bK2lAfqRtuwxH-tNqAytiK?usp=sharing) and [Baidu Netdisk](https://pan.baidu.com/s/1QqjOlAAjCqAk_qL6ejeARw?pwd=TwVi) (code: TwVi).
