### ISSUE TITLE
The problem of model reproduction

### ISSUE THREAD

**Issue by 10652835** [NUSTM/FMNERG#3]
![WeChat1d452dbadd9e06207a5e80648f4284ff](https://github.com/NUSTM/FMNERG/assets/29936727/7f977c40-d9ad-4b73-9919-9b5587bcaa88)
I tried to reproduce the effect of the model, but there is a certain gap with the effect reported in the paper. Does anyone have a similar problem with me.

**Comment by zyLiRere** [comment]
Apologies for the mistake in the VinVL feature upload. We've resolved the issue. To access the precise features, please use the provided links: [Google Drive](https://drive.google.com/drive/folders/1w7W4YYeIE6bK2lAfqRtuwxH-tNqAytiK?usp=sharing) and [Baidu Netdisk](https://pan.baidu.com/s/1QqjOlAAjCqAk_qL6ejeARw?pwd=TwVi) (code: TwVi).

**Comment by YuanLi95** [comment]
> ![WeChat1d452dbadd9e06207a5e80648f4284ff](https://private-user-images.githubusercontent.com/29936727/286257412-7f977c40-d9ad-4b73-9919-9b5587bcaa88.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyOTM1ODQsIm5iZiI6MTcxMDI5MzI4NCwicGF0aCI6Ii8yOTkzNjcyNy8yODYyNTc0MTItN2Y5NzdjNDAtZDlhZC00YjczLTk5MTktOWI1NTg3YmNhYTg4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDAxMjgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1ZGIyYjJlYjEzZTdhMTU1MWNjOWQwYjAyYTE0YzM0M2NkYjFlZTU0NWNjOWNjY2JhNDI5MWM4MWM2MWZmYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P2NQos3D7tKZ6-7V6t0Efdh5zTWPVrYqRH5lb2a5j88) I tried to reproduce the effect of the model, but there is a certain gap with the effect reported in the paper. Does anyone have a similar problem with me.

我在运行改论文的代码时遇到一些问题，请问能沟通一下吗？

**Comment by 10652835** [comment]
可以，什么问题啊？

**Comment by YuanLi95** [comment]
能加微信吗？ 老哥&nbsp;a374702739

袁理，SCUT



ip135y
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NUSTM/FMNERG"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月13日(星期三) 上午9:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NUSTM/FMNERG] The problem of model reproduction (Issue #3)





 
可以，什么问题啊？
