### ISSUE TITLE
With the code in the repo, it cannot automatically save the model, and the modelcheckpoint output best model path '' and best value 0?

### ISSUE THREAD

**Issue by ZihaoZheng98** [NUSTM/FMNERG#6]

**Comment by ZihaoZheng98** [comment]
<img width="1131" alt="image" src="https://github.com/NUSTM/FMNERG/assets/22414831/a0d72a4d-d4d6-497e-8d3b-c0696a8ba59e">

**Comment by ZihaoZheng98** [comment]
It seems that the modelcheckpoint does not monitor val_loss.

**Comment by zyLiRere** [comment]
Could you confirm the PyTorch Lightning version you're currently using? Ensuring it aligns with our requirements mentioned in 'requirement.txt' would be beneficial for consistency.

**Comment by ZihaoZheng98** [comment]
> Could you confirm the PyTorch Lightning version you're currently using? Ensuring it aligns with our requirements mentioned in 'requirement.txt' would be beneficial for consistency.

Hi, with the version in the repo, I still cannot run it correctly. I have tested several versions and finally found that version 0.7 works. Pytorch-lightning is too complex to use for me~. Many thanks any way.
